# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/coral/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),coral)

$(call add-radio-file-sha1-checked,radio/abl.img,455dd4de77c767db7cce8416556a59c4731cd3af)
$(call add-radio-file-sha1-checked,radio/aop.img,6f38268c5335e236b1a743c82045274052e3b9d2)
$(call add-radio-file-sha1-checked,radio/devcfg.img,0548b001db1993f7f236984b134def3dfc00135e)
$(call add-radio-file-sha1-checked,radio/hyp.img,9b840bffcc4843d5f693f9e1dc835831957b1fc3)
$(call add-radio-file-sha1-checked,radio/keymaster.img,662b6b586a3c5f942d22cbf836c8b2a73165cdff)
$(call add-radio-file-sha1-checked,radio/modem.img,a7c222c1056ff95be7bef72b7d3356e3548d4496)
$(call add-radio-file-sha1-checked,radio/qupfw.img,6fbea04b8e43d9474e1b2b2aee0fc343e7c71af0)
$(call add-radio-file-sha1-checked,radio/tz.img,7a65a5603bef36cf78984d43b8b9ef63fb0db2fa)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,0333b045dd2a6cf44be0a7fe1d94f4122a563005)
$(call add-radio-file-sha1-checked,radio/xbl.img,a34cfed521432cb11263e875994493c6dcfb408d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,73dfe41c83d069611f68aaf695e02f0d85b909c2)

endif
